# Generated by Django 3.0.7 on 2020-06-26 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Nome')),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('e_mail', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('password', models.CharField(max_length=50, verbose_name='Senha')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Data Criação')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Application')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Data/Hora')),
                ('level', models.CharField(choices=[('E', 'Erro'), ('C', 'Crítico'), ('W', 'Aviso'), ('I', 'Informativo'), ('D', 'Modo Dev.')], default='E', max_length=11, verbose_name='Nível')),
                ('ip_address', models.GenericIPAddressField(unpack_ipv4=True, verbose_name='Endereço IP')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.User')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Environment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Application')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='environment',
            field=models.ManyToManyField(to='api.Environment'),
        ),
    ]
