# Generated by Django 3.0.7 on 2020-06-26 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200626_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='user_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(null=True, verbose_name='Último Acesso'),
        ),
        migrations.AlterField(
            model_name='event',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Application'),
        ),
        migrations.AlterField(
            model_name='event',
            name='level',
            field=models.CharField(choices=[('E', 'Erro'), ('C', 'Crítico'), ('W', 'Aviso'), ('I', 'Informativo'), ('D', 'Modo Dev.')], max_length=11, verbose_name='Nível'),
        ),
    ]
