# Generated by Django 3.0.7 on 2020-06-26 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200626_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='application',
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.User'),
            preserve_default=False,
        ),
    ]
