# Generated by Django 3.0.7 on 2020-07-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200626_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='occurrences',
            field=models.IntegerField(null=True),
        ),
    ]
